from scrapy.item import Item, Field

class ContractorItem(Item):
    name = Field()
    url = Field()
    description = Field()
    category = Field()
    rating = Field()
    rating_buildzoom = Field()
    phone = Field()
    email = Field()
    website = Field()
    is_licensed = Field()
    license_info = Field()
    insured_value = Field()
    bond_value = Field()
    street_address = Field()
    city = Field()
    state = Field()
    zipcode = Field()
    full_address = Field()
    image_urls = Field()
    images = Field()
    info_updated_at = Field()
    employee = Field()
    work_preferences = Field()
